### ISSUE TITLE
Ruby 2.2 Support

### ISSUE THREAD

**Issue by Intrepidd** [mroth/lolcommits#248]
Hi,

Thanks for the gem.

Just to let you know, build fails on ruby 2.2

Here's the build error :

```
make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/adrien/.rubies/mri-2.2/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2
```

Thanks, and happy holidays

**Comment by nirozjung** [comment]
Hi, I had same error failing the build with json1.6.6 in ruby 2.2.3. Tried to install json 1.6.6 from  (https://github.com/kgrz/json). Again it failed giving the following error. Any suggestions?

GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Bundler version 1.10.6
fatal: Not a git repository (or any of the parent directories): .git
cd ext/json/ext/parser
/usr/local/var/rbenv/versions/2.2.3/bin/ruby extconf.rb
creating Makefile
make
compiling parser.c
In file included from parser.rl:1:
./../fbuffer/fbuffer.h:151:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/usr/local/var/rbenv/versions/2.2.3/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from parser.rl:1:
./../fbuffer/fbuffer.h:151:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an
      expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [parser.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/Users/nirozjungkarki/Downloads/json-1.6.6/Rakefile:311:in `block (2 levels) in <top (required)>'
/Users/nirozjungkarki/Downloads/json-1.6.6/Rakefile:309:in `block in <top (required)>'
Tasks: TOP => install => install_ext => compile => ext/json/ext/parser/parser.bundle
(See full trace by running task with --trace)

**Comment by matthutchinson** [comment]
Ok, will take a look soon and see if moving the gem version for json can help here.

**Comment by matthutchinson** [comment]
So the latest lolcommits gem requires `json ~> 1.8.1` already - I'm not sure why you're trying to install `1.6.6`.  

For me, installing lolcommits on a fresh mac with Ruby 2.2.2 (or 2.2.3) works without any issues. Also `json 1.8.1` is now part of the default gem set installed with a fresh copy of Ruby 2.2.3.

I'm going to close this issue for now. If you have issues with other versions of the `json` gem please add them at their repo.
